server:
  port: 7000
spring:
  application:
    name: ConsumerUserFeign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
# 开启Feign的熔断功能
feign:
  hystrix:
    enabled: true
#暴露数据监控流
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream #访问/actuator/hystrix.stream能看到不断更新的监控流
# 开启可视化监控功能
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
