server:
  port: 8761
spring:
  application:
    name: SCWERGISTER
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true #安全保护
    eviction-interval-timer-in-ms: 5000
  client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}
#注册中心
